name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  PYTEST_ADDOPTS: "--color=yes"

permissions:
  contents: read

jobs:
  test:
    name: Test - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uv run pytest
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Validate links in Markdown files
        uses: JustinBeckwith/linkinator-action@363572b2714d25a059fceb2fa332a98e7ea3baff # v2.4
        with:
          retry: true
      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          cache: true
      - name: Run linting
        run: mise run ci
