name: Build & maybe upload PyPI package

on:
  push:
    branches: [main]
  release:
    types:
      - published
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

jobs:
  # Always build & lint package.
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: baipp
        uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
    outputs:
      package_version: ${{ steps.baipp.outputs.package_version }}
  # Upload to Test PyPI on every commit on main.
  release-test-pypi:
    permissions:
      contents: read
      id-token: write
    if: github.repository_owner == 'bryanwweber' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Publish in-dev package to test.pypi.org
    environment: release-test-pypi
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: Packages
          path: dist
      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
  # Upload to real PyPI on GitHub Releases.
  release-pypi:
    permissions:
      contents: read
      id-token: write
    name: Publish released package to pypi.org
    environment: release-pypi
    if: github.repository_owner == 'bryanwweber' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          verbose: true
